# SPDX-FileCopyrightText: 2023-2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT

name: Unit tests

on:
    pull_request:
        branches: [ master, main, stable-* ]
    push:
        branches: [ master, main, stable-* ]

permissions:
    contents: read
    pull-requests: write

concurrency:
    group: unit-tests-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
                with:
                    persist-credentials: false

            -   name: Set up JDK 17
                uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
                with:
                    distribution: "temurin"
                    java-version: 17

            -   name: Setup Gradle
                uses: gradle/actions/setup-gradle@017a9effdb900e5b5b2fddfb590a105619dca3c3 # v4.4.2

            -   name: Run unit tests with coverage
                run: ./gradlew testGplayDebugUnit

            -   name: Upload test artifacts
                if: ${{ failure() }}
                uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
                with:
                    name: test-results
                    path: app/build/reports/tests/testGplayDebugUnitTest/
